### ISSUE TITLE
Parts list for level conversion board

### ISSUE THREAD

**Issue by jsmitchell** [ryomuk/gu3000#2]
Hi, nice project! Do you have a BOM or parts list for the level converter board? Thanks!

**Comment by ryomuk** [comment]
Thank you!
I have not made a BOM. Just a schematic.
https://github.com/ryomuk/gu3000/blob/main/hardware/GU3000RasPiIF-schematics.pdf

**Comment by jsmitchell** [comment]
Ok, thanks! I tried to infer reasonable parts and sizes from the schematic. I've included a table below. If you have a few minutes could you take a quick look and provide any guidance if anything seem incorrect?

| Schematic ID | Part | Size | Link |
| -------------  | ---- | ---- | ---- |
| CN1 | Conn_02x20 | | https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC020DFBN-RC/2775474 |
| CN2 | Conn_02x08 | | https://www.digikey.com/en/products/detail/würth-elektronik/61201621621/2060591
| CN3 | Conn_01x02 | | https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC001DFBN-RC/2775493 |
| CN4 | Conn_01x02 | | https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC001DFBN-RC/2775493 |
| U1 | SN74ABT827DW | | https://www.digikey.com/en/products/detail/texas-instruments/SN74ABT827DW/375747 |
| U2 | SN74LVC1G17DBVR | | https://www.digikey.com/en/products/detail/texas-instruments/SN74LVC1G17DBVR/389051 |
| R1 | 100k | 0805 | https://www.digikey.com/en/products/detail/yageo/RC0805FR-07100KL/727544 |
| C1 | 0.1uF | 0805 | https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL21B104KBFXPJE/11487741 |
| C2 | 0.1uF | 0805 | https://www.digikey.com/en/products/detail/samsung-electro-mechanics/CL21B104KBFXPJE/11487741 |
| C3 | 10uF | 1206 | https://www.digikey.com/en/products/detail/taiyo-yuden/TMK316B7106KL-TD/2178918 |
| J1 | Barrel_Jack | | https://www.digikey.com/en/products/detail/cui-devices/PJ-002A/96962 |
| J2 | PinHdr_01x02 | | https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC001DFBN-RC/2775493 |
| J3 | PinHdr_01x02 | | https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC001DFBN-RC/2775493 |

**Comment by ryomuk** [comment]
Hi,
CN1 connects to the RasPi GPIO pin header, so it is a female socket such as;
https://www.digikey.jp/en/products/detail/sullins-connector-solutions/PPPC202LFBN-RC/810259
CN3 and CN4 are optional and you don't need them.
J2 and J3 can be integrated into a 2x2 pin header.
https://www.digikey.com/en/products/detail/sullins-connector-solutions/PRPC002DAAN-RC/2775292
The other parts seems to be fine.
Thanks,
